# Use the official Python image from the Docker Hub
FROM python:3.11-slim

WORKDIR /app
# Copy the requirements file into the container
COPY  api/requirements.txt .
RUN apt-get update && apt-get install -y --no-install-recommends \
    libgomp1 \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
# Install the required Python packages
RUN pip install --no-cache-dir -r requirements.txt
# Copy the FastAPI application code into the container
COPY api/api.py .
# Expose the port that the app will run on
EXPOSE 8000
# Command to run the FastAPI application using Uvicorn
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]